// <auto-generated />
using System;
using EventHandler.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EventHandler.DAL.Migrations
{
    [DbContext(typeof(EventHandlerDbContext))]
    [Migration("20200226150556_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EventHandler.DAL.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Applicant")
                        .IsRequired()
                        .HasColumnName("applicant")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ApplicantDepartment")
                        .HasColumnName("applicant_department")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("ApplyDateTime")
                        .HasColumnName("apply_date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<long>("EventStatusId")
                        .HasColumnName("event_status_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolveDateTime")
                        .HasColumnName("resolve_date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Resolver")
                        .HasColumnName("resolver")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Responsible")
                        .HasColumnName("responsible")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("EventStatusId");

                    b.HasIndex("Id");

                    b.ToTable("event");
                });

            modelBuilder.Entity("EventHandler.DAL.Entities.EventStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SysName")
                        .IsRequired()
                        .HasColumnName("sys_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("event_status");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            SysName = "pending"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            SysName = "in_progress"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            SysName = "done"
                        });
                });

            modelBuilder.Entity("EventHandler.DAL.Entities.Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnName("locale")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnName("text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Locale")
                        .IsUnique();

                    b.ToTable("resource");

                    b.HasData(
                        new
                        {
                            Id = "AppName_Label",
                            Locale = "EN",
                            Text = "EventHandler"
                        },
                        new
                        {
                            Id = "AppBar_Login_Label",
                            Locale = "EN",
                            Text = "Login"
                        },
                        new
                        {
                            Id = "AppBar_Create_Event_Label",
                            Locale = "EN",
                            Text = "Create Event"
                        },
                        new
                        {
                            Id = "AppBar_Event_List_Label",
                            Locale = "EN",
                            Text = "Event List"
                        },
                        new
                        {
                            Id = "AppBar_Reports_Label",
                            Locale = "EN",
                            Text = "Reports"
                        },
                        new
                        {
                            Id = "AppBar_Reports_Administration",
                            Locale = "EN",
                            Text = "Administration"
                        },
                        new
                        {
                            Id = "AppBar_Reports_Settings",
                            Locale = "EN",
                            Text = "Settings"
                        },
                        new
                        {
                            Id = "EventsTable_Header_FullName",
                            Locale = "EN",
                            Text = "FullName"
                        },
                        new
                        {
                            Id = "EventsTable_Header_ApplyDateTime",
                            Locale = "EN",
                            Text = "Date Time"
                        },
                        new
                        {
                            Id = "EventsTable_Header_Description",
                            Locale = "EN",
                            Text = "Description"
                        },
                        new
                        {
                            Id = "EventsTable_Header_Responsible",
                            Locale = "EN",
                            Text = "Responsible"
                        },
                        new
                        {
                            Id = "EventsTable_Header_Status",
                            Locale = "EN",
                            Text = "Status"
                        },
                        new
                        {
                            Id = "EventsTable_Header_ResolveDateTime",
                            Locale = "EN",
                            Text = "Resolving Date Time"
                        },
                        new
                        {
                            Id = "CreateEvent_FullName_Label",
                            Locale = "EN",
                            Text = "FullName"
                        },
                        new
                        {
                            Id = "CreateEvent_Department_Label",
                            Locale = "EN",
                            Text = "Department"
                        },
                        new
                        {
                            Id = "CreateEvent_Description_Label",
                            Locale = "EN",
                            Text = "Description"
                        },
                        new
                        {
                            Id = "CreateEvent_Submit_Button_Label",
                            Locale = "EN",
                            Text = "Submit"
                        });
                });

            modelBuilder.Entity("EventHandler.DAL.Entities.Event", b =>
                {
                    b.HasOne("EventHandler.DAL.Entities.EventStatus", "EventStatus")
                        .WithMany("Events")
                        .HasForeignKey("EventStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
