// <auto-generated />
using System;
using EventHandler.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EventHandler.DAL.Migrations
{
    [DbContext(typeof(EventHandlerDbContext))]
    partial class EventHandlerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EventHandler.DAL.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Applicant")
                        .IsRequired()
                        .HasColumnName("applicant")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ApplicantDepartment")
                        .HasColumnName("applicant_department")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("ApplyDateTime")
                        .HasColumnName("apply_date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<long>("EventStatusId")
                        .HasColumnName("event_status_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolveDateTime")
                        .HasColumnName("resolve_date_time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Resolver")
                        .HasColumnName("resolver")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Responsible")
                        .HasColumnName("responsible")
                        .HasColumnType("character varying(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("EventStatusId");

                    b.HasIndex("Id");

                    b.ToTable("event");
                });

            modelBuilder.Entity("EventHandler.DAL.Entities.EventStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SysName")
                        .IsRequired()
                        .HasColumnName("sys_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("event_status");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            SysName = "pending"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            SysName = "in_progress"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            SysName = "done"
                        });
                });

            modelBuilder.Entity("EventHandler.DAL.Entities.Event", b =>
                {
                    b.HasOne("EventHandler.DAL.Entities.EventStatus", "EventStatus")
                        .WithMany("Events")
                        .HasForeignKey("EventStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
